package com.fanmes.common.security;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fanmes.common.exception.BusinessException;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.*; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Component; import org.springframework.util.StringUtils;
@Component public class JwtTokenService {
 private final ObjectMapper mapper; private final String secret; private final String issuer; private final long ttl;
 public JwtTokenService(ObjectMapper mapper,@Value("${fanmes.jwt.secret:${FANMES_JWT_SECRET:fan-mes-change-this-development-secret-2026}}") String secret,@Value("${fanmes.jwt.issuer:fan-mes}") String issuer,@Value("${fanmes.jwt.expires-in-seconds:28800}") long ttl){this.mapper=mapper;this.secret=secret;this.issuer=issuer;this.ttl=ttl;}
 public String createToken(Long uid,String username,Collection<String> roles,Collection<String> permissions){try{long now=Instant.now().getEpochSecond();Map<String,Object> c=new LinkedHashMap<>();c.put("iss",issuer);c.put("sub",username);c.put("uid",uid);c.put("roles",roles==null?Set.of():roles);c.put("permissions",permissions==null?Set.of():permissions);c.put("iat",now);c.put("exp",now+ttl);String head=enc(Map.of("alg","HS256","typ","JWT"));String body=enc(c);return head+"."+body+"."+sign(head+"."+body);}catch(Exception e){throw new BusinessException("JWT 创建失败");}}
 public AuthenticatedUser verify(String auth){try{if(!StringUtils.hasText(auth)||!auth.regionMatches(true,0,"Bearer ",0,7))throw new IllegalArgumentException();String[] p=auth.substring(7).trim().split("\\.");if(p.length!=3||!MessageDigest.isEqual(sign(p[0]+"."+p[1]).getBytes(StandardCharsets.US_ASCII),p[2].getBytes(StandardCharsets.US_ASCII)))throw new IllegalArgumentException();Map<String,Object> c=mapper.readValue(Base64.getUrlDecoder().decode(p[1]),new TypeReference<>(){});if(!issuer.equals(c.get("iss"))||((Number)c.get("exp")).longValue()<=Instant.now().getEpochSecond())throw new IllegalArgumentException();return new AuthenticatedUser(((Number)c.get("uid")).longValue(),String.valueOf(c.get("sub")),set(c.get("roles")),set(c.get("permissions")));}catch(Exception e){throw new BusinessException("无效或已过期的 token");}}
 private String enc(Object v)throws Exception{return Base64.getUrlEncoder().withoutPadding().encodeToString(mapper.writeValueAsBytes(v));} private String sign(String s)throws Exception{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(m.doFinal(s.getBytes(StandardCharsets.US_ASCII)));} private Set<String> set(Object v){if(!(v instanceof Collection<?> c))return Set.of();Set<String>s=new LinkedHashSet<>();c.forEach(x->s.add(String.valueOf(x)));return Set.copyOf(s);}
}
