<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getAndonExceptions } from '@/api/production'
const rows = ref<Record<string, unknown>[]>([]); const error = ref(''); const loading = ref(false)
const value = (row: Record<string, unknown>, key: string) => String(row[key] ?? '-')
async function load() { loading.value = true; error.value = ''; try { rows.value = await getAndonExceptions() } catch (e) { error.value = e instanceof Error ? e.message : '安灯异常加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="andon"><header class="app-header"><div class="header-breadcrumb"><span>设备与安灯</span><span class="bc-sep">/</span><span class="bc-current">安灯异常</span></div><div class="header-actions"><span class="badge badge-status-error"><span class="badge-dot"></span>{{ rows.length }} 条未关闭</span><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">安灯异常处理</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>异常编号</th><th>异常类型</th><th>产线</th><th>工单</th><th>发生时间</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="6">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="6">暂无安灯异常</td></tr><tr v-for="(row, index) in rows" :key="String(row.id || index)"><td class="cell-mono">{{ value(row, 'andonNo') }}</td><td>{{ value(row, 'exceptionType') }}</td><td>{{ value(row, 'lineId') }}</td><td>{{ value(row, 'workOrderId') }}</td><td>{{ value(row, 'triggeredAt') }}</td><td><span class="badge badge-status-warn"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">安灯异常 · {{ rows.length }} 条</span></footer></MesLayout></template>
