<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, postProductionAction, type ResourceRecord } from '@/api/production'
const rows = ref<ResourceRecord[]>([]); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
async function load() { error.value = ''; try { rows.value = await getProductionRecords('/production/barcodes/rules') } catch (e) { error.value = e instanceof Error ? e.message : '条码规则加载失败' } }
async function action(row: ResourceRecord, name: string) { if (!row.id) return; try { await postProductionAction(`/production/barcodes/rules/${row.id}/${name}`, { reason: '页面操作' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '规则操作失败' } }
onMounted(load)
</script>
<template><MesLayout active="barcode-rules"><header class="app-header"><div class="header-breadcrumb"><span>条码与追溯</span><span class="bc-sep">/</span><span class="bc-current">条码规则</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">条码规则管理</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>规则编码</th><th>规则名称</th><th>条码类型</th><th>编码表达式</th><th>流水号长度</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="7">暂无条码规则</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'ruleCode') }}</td><td>{{ value(row, 'ruleName') }}</td><td>{{ value(row, 'typeName') }}</td><td class="cell-mono">{{ value(row, 'ruleExpression') }}</td><td>{{ value(row, 'serialLength') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><button class="btn btn-ghost btn-sm" @click="action(row, 'enable')">启用</button><button class="btn btn-ghost btn-sm" @click="action(row, 'disable')">停用</button></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">条码规则 · {{ rows.length }} 条</span></footer></MesLayout></template>
