<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, postProductionAction, type ResourceRecord } from '@/api/production'
const keyword = ref(''); const rows = ref<ResourceRecord[]>([]); const loading = ref(false); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
async function load() { loading.value = true; error.value = ''; try { rows.value = await getProductionRecords('/production/barcodes', { keyword: keyword.value || undefined }) } catch (e) { error.value = e instanceof Error ? e.message : '条码记录加载失败' } finally { loading.value = false } }
async function action(row: ResourceRecord, name: string) { if (!row.id) return; try { await postProductionAction(`/production/barcodes/${row.id}/${name}`, { remark: '页面操作' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : '条码操作失败' } }
onMounted(load)
</script>
<template><MesLayout active="barcode"><header class="app-header"><div class="header-breadcrumb"><span>条码与追溯</span><span class="bc-sep">/</span><span class="bc-current">条码管理</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">条码管理</h1><div class="card mb-5"><div class="search-bar" style="margin-bottom:0"><div class="form-group" style="min-width:180px"><label class="form-label">条码值</label><input v-model="keyword" class="form-input" placeholder="搜索条码..." @keyup.enter="load"></div><button class="btn btn-secondary btn-sm" style="align-self:flex-end" @click="load">查询</button></div></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>条码值</th><th>类型</th><th>物料编码</th><th>物料名称</th><th>批次</th><th>生产工单</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="8">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="8">暂无条码记录</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'barcodeValue') }}</td><td>{{ value(row, 'typeName') }}</td><td>{{ value(row, 'itemCode') }}</td><td>{{ value(row, 'itemName') }}</td><td>{{ value(row, 'batchNo') }}</td><td>{{ value(row, 'workOrderNo') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><button class="btn btn-ghost btn-sm" @click="action(row, 'close')">关闭</button><button class="btn btn-ghost btn-sm" @click="action(row, 'void')">作废</button></td></tr></tbody></table><div class="pagination">共 {{ rows.length }} 条记录</div></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">条码记录 · {{ rows.length }} 条</span></footer></MesLayout></template>
