<script setup lang="ts">
import { ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { post } from '@/api/client'
type ScanRecord = { barcodeValue?: string; typeName?: string; itemCode?: string; itemName?: string; workOrderNo?: string; batchNo?: string; status?: string }
const scanValue = ref(''); const result = ref<ScanRecord | null>(null); const error = ref(''); const loading = ref(false)
async function scan() { if (!scanValue.value.trim()) return; loading.value = true; error.value = ''; try { result.value = await post<ScanRecord>('/production/barcodes/scan', { barcodeValue: scanValue.value.trim(), eventType: 'SCAN' }) } catch (e) { error.value = e instanceof Error ? e.message : '扫码失败' } finally { loading.value = false } }
</script>
<template><MesLayout active="scan"><header class="app-header"><div class="header-breadcrumb"><span>条码与追溯</span><span class="bc-sep">/</span><span class="bc-current">扫码终端</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">扫码终端</h1><div style="display:grid;grid-template-columns:1fr 1fr;gap:var(--space-5)"><section class="card"><div class="card-header"><h2 class="card-title">扫码输入</h2></div><div class="form-group mb-4"><label class="form-label">条码值</label><div class="flex gap-2"><input v-model="scanValue" class="form-input" placeholder="扫描或手动输入条码..." autofocus @keydown.enter="scan"><button class="btn btn-primary" :disabled="loading" @click="scan">{{ loading ? '处理中...' : '解析' }}</button></div></div><div class="text-muted" style="font-size:var(--text-caption)">支持扫码枪自动回车</div><div v-if="error" class="alert alert-error mt-4"><span class="alert-icon">!</span>{{ error }}</div></section><section v-if="result" class="card"><div class="card-header"><h2 class="card-title">数据库解析结果</h2></div><table class="data-table" style="border:none"><tbody><tr><td>条码值</td><td class="cell-mono">{{ result.barcodeValue }}</td></tr><tr><td>类型</td><td>{{ result.typeName }}</td></tr><tr><td>物料/产品</td><td>{{ result.itemCode }} {{ result.itemName }}</td></tr><tr><td>关联工单</td><td>{{ result.workOrderNo || '-' }}</td></tr><tr><td>批次</td><td>{{ result.batchNo || '-' }}</td></tr><tr><td>状态</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ result.status }}</span></td></tr></tbody></table></section></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>扫码终端</span></footer></MesLayout></template>
