<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { get } from '@/api/client'
type MaintenanceRow = Record<string, unknown> & { id?: string | number }
const activeTab = ref<'plans' | 'records'>('plans'); const rows = ref<MaintenanceRow[]>([]); const loading = ref(false); const error = ref('')
const value = (row: MaintenanceRow, ...keys: string[]) => String(keys.map((key) => row[key]).find((item) => item !== undefined && item !== null) ?? '-')
const planned = computed(() => rows.value.filter((row) => !/completed|closed|完成|关闭/i.test(value(row, 'status')))); const records = computed(() => rows.value.filter((row) => /completed|closed|完成|关闭/i.test(value(row, 'status'))))
async function load() { loading.value = true; error.value = ''; try { const response = await get<unknown>('/equipment/maintenance-tasks'); rows.value = Array.isArray(response) ? response as MaintenanceRow[] : Array.isArray((response as { records?: unknown })?.records) ? (response as { records: MaintenanceRow[] }).records : [] } catch (reason) { rows.value = []; error.value = reason instanceof Error ? reason.message : '保养任务加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="equip-maint"><header class="app-header"><div class="header-breadcrumb"><span>设备与安灯</span><span class="bc-sep">/</span><span class="bc-current">点检保养</span></div><div class="header-actions"><button class="btn btn-secondary btn-sm" :disabled="loading" @click="load">刷新</button><span class="user-avatar">张</span></div></header><main class="app-main" data-od-id="maint-main"><h1 class="page-title">点检保养</h1><div class="tabs" data-od-id="maint-tabs"><button class="tab-item" :class="{ active: activeTab === 'plans' }" @click="activeTab = 'plans'">保养计划</button><button class="tab-item" :class="{ active: activeTab === 'records' }" @click="activeTab = 'records'">执行记录</button></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table v-if="activeTab === 'plans'" class="data-table"><thead><tr><th>计划编号</th><th>设备</th><th>保养类型</th><th>计划日期</th><th>负责人</th><th>内容摘要</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="7">正在加载...</td></tr><tr v-else-if="!planned.length"><td colspan="7" class="text-muted">暂无待执行保养计划</td></tr><tr v-for="(row, index) in planned" :key="row.id ?? index"><td class="cell-mono">{{ value(row, 'maintenanceNo', 'taskNo', 'id') }}</td><td>{{ value(row, 'equipmentName', 'equipmentId') }}</td><td>{{ value(row, 'maintenanceType', 'type') }}</td><td>{{ value(row, 'planAt', 'planDate') }}</td><td>{{ value(row, 'assignedTo', 'ownerName') }}</td><td>{{ value(row, 'content', 'remark') }}</td><td><span class="badge badge-status-info"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td></tr></tbody></table><table v-else class="data-table"><thead><tr><th>记录编号</th><th>设备</th><th>保养类型</th><th>执行时间</th><th>执行人</th><th>耗时</th><th>结果</th><th>异常备注</th></tr></thead><tbody><tr v-if="loading"><td colspan="8">正在加载...</td></tr><tr v-else-if="!records.length"><td colspan="8" class="text-muted">暂无执行记录</td></tr><tr v-for="(row, index) in records" :key="row.id ?? index"><td class="cell-mono">{{ value(row, 'recordNo', 'maintenanceNo', 'id') }}</td><td>{{ value(row, 'equipmentName', 'equipmentId') }}</td><td>{{ value(row, 'maintenanceType', 'type') }}</td><td>{{ value(row, 'executedAt', 'completedAt') }}</td><td>{{ value(row, 'executedBy', 'assignedTo') }}</td><td>{{ value(row, 'duration') }}</td><td>{{ value(row, 'result', 'status') }}</td><td>{{ value(row, 'exceptionRemark', 'remark') }}</td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>系统正常</span><span class="statusbar-sep">|</span><span class="statusbar-item">点检保养 · {{ planned.length }} 条计划 · {{ records.length }} 条记录</span><span class="statusbar-sep">|</span><span class="statusbar-item" style="margin-left:auto">AeroForge MES v2.0</span></footer></MesLayout></template>
