<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, type ResourceRecord } from '@/api/production'
const rows = ref<ResourceRecord[]>([]); const loading = ref(false); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
const completed = computed(() => rows.value.filter((row) => String(row.status).includes('COMPLETE')).length)
async function load() { loading.value = true; error.value = ''; try { rows.value = await getProductionRecords('/production/kitting-analyses') } catch (e) { error.value = e instanceof Error ? e.message : '齐套分析加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="kitting"><header class="app-header"><div class="header-breadcrumb"><span>生产管理</span><span class="bc-sep">/</span><span class="bc-current">齐套分析</span></div><div class="header-actions"><button class="btn btn-secondary btn-sm" @click="load">刷新分析</button><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">齐套分析</h1><div class="kpi-grid" style="grid-template-columns:repeat(4,1fr)"><div class="kpi-card accent-border"><span class="kpi-label">分析记录</span><span class="kpi-value">{{ rows.length }}</span><span class="kpi-change">数据库实时数据</span></div><div class="kpi-card"><span class="kpi-label">已完成</span><span class="kpi-value">{{ completed }}</span><span class="kpi-change up">分析完成</span></div></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><section class="card mb-5"><div class="card-header"><h2 class="card-title">齐套分析结果</h2></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>分析编号</th><th>工单</th><th>状态</th><th>分析时间</th><th>备注</th></tr></thead><tbody><tr v-if="loading"><td colspan="5">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="5">暂无分析记录</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'analysisNo') }}</td><td>{{ value(row, 'workOrderId') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td>{{ value(row, 'analyzedAt') }}</td><td>{{ value(row, 'remark') }}</td></tr></tbody></table></div></section></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">齐套分析 · {{ rows.length }} 条</span></footer></MesLayout></template>
