<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, postProductionAction, type ResourceRecord } from '@/api/production'
const rows = ref<ResourceRecord[]>([]); const loading = ref(false); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
async function load() { loading.value = true; error.value = ''; try { rows.value = await getProductionRecords('/production/tasks') } catch (e) { error.value = e instanceof Error ? e.message : '生产任务加载失败' } finally { loading.value = false } }
async function action(row: ResourceRecord, name: string) { if (!row.id) return; try { await postProductionAction(`/production/tasks/${row.id}/${name}`); await load() } catch (e) { error.value = e instanceof Error ? e.message : '任务操作失败' } }
onMounted(load)
</script>
<template><MesLayout active="tasks"><header class="app-header"><div class="header-breadcrumb"><span>生产管理</span><span class="bc-sep">/</span><span class="bc-current">生产任务</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">生产任务</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>任务编号</th><th>关联派工</th><th>工序</th><th>计划数量</th><th>已完工</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="7">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="7">暂无生产任务</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'taskNo') }}</td><td>{{ value(row, 'dispatchOrderId') }}</td><td>{{ value(row, 'operationId') }}</td><td>{{ value(row, 'planQty') }}</td><td>{{ value(row, 'completedQty') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><button class="btn btn-ghost btn-sm" @click="action(row, 'start')">开工</button><button class="btn btn-ghost btn-sm" @click="action(row, 'pause')">暂停</button><button class="btn btn-ghost btn-sm" @click="action(row, 'complete')">完工</button></td></tr></tbody></table><div class="pagination">共 {{ rows.length }} 条记录</div></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">生产任务 · {{ rows.length }} 项</span></footer></MesLayout></template>
