<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, type ResourceRecord } from '@/api/production'
const rows = ref<ResourceRecord[]>([]); const loading = ref(false); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
const totalShortage = computed(() => rows.value.reduce((sum, row) => sum + Number(row.shortageQty || 0), 0))
async function load() { loading.value = true; error.value = ''; try { rows.value = await getProductionRecords('/production/kitting-missing-board') } catch (e) { error.value = e instanceof Error ? e.message : '缺料看板加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="kboard"><header class="app-header"><div class="header-breadcrumb"><span>生产管理</span><span class="bc-sep">/</span><span class="bc-current">缺料看板</span></div><div class="header-actions"><span class="badge badge-status-error"><span class="badge-dot"></span>{{ rows.length }} 项缺料</span><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">齐套缺料看板</h1><div class="kb-summary"><div class="kb-summary-stat"><span class="kbs-label">缺料项</span><span class="kbs-value accent">{{ rows.length }}</span></div><div class="kb-summary-sep"></div><div class="kb-summary-stat"><span class="kbs-label">总缺口</span><span class="kbs-value">{{ totalShortage }}</span></div></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>工单</th><th>物料</th><th>需求数量</th><th>现有数量</th><th>缺口</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="6">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="6">暂无缺料记录</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'workOrderNo') }}</td><td>{{ value(row, 'materialName') }}</td><td>{{ value(row, 'requiredQty') }}</td><td>{{ value(row, 'availableQty') }}</td><td>{{ value(row, 'shortageQty') }}</td><td><span class="badge badge-status-warn"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot warn"></span>缺料看板 · {{ rows.length }} 项</span></footer></MesLayout></template>
