<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getProductionRecords, type ResourceRecord } from '@/api/production'
const keyword = ref(''); const rows = ref<ResourceRecord[]>([]); const loading = ref(false); const error = ref('')
const value = (row: ResourceRecord, key: string) => String(row[key] ?? '-')
async function load() { loading.value = true; error.value = ''; try { rows.value = await getProductionRecords('/production/dispatch-orders', { keyword: keyword.value || undefined }) } catch (e) { error.value = e instanceof Error ? e.message : '派工单加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="dispatch"><header class="app-header"><div class="header-breadcrumb"><span>生产管理</span><span class="bc-sep">/</span><span class="bc-current">派工单</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">派工单管理</h1><div class="card mb-5"><div class="search-bar" style="margin-bottom:0"><div class="form-group" style="min-width:180px"><label class="form-label">派工单号</label><input v-model="keyword" class="form-input" placeholder="搜索派工单号..." @keyup.enter="load"></div><button class="btn btn-secondary btn-sm" style="align-self:flex-end" @click="load">查询</button></div></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>派工单号</th><th>关联工单</th><th>产线</th><th>工序</th><th>计划数量</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="6">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="6">暂无派工单</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'dispatchNo') }}</td><td>{{ value(row, 'workOrderId') }}</td><td>{{ value(row, 'lineId') }}</td><td>{{ value(row, 'operationId') }}</td><td>{{ value(row, 'planQty') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td></tr></tbody></table><div class="pagination">共 {{ rows.length }} 条记录</div></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>数据库实时数据</span><span class="statusbar-sep">|</span><span class="statusbar-item">派工单 · {{ rows.length }} 条</span></footer></MesLayout></template>
