<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getQualityRecords, postQualityAction, type QualityRecord } from '@/api/quality'
const rows = ref<QualityRecord[]>([]); const error = ref(''); const value = (row: QualityRecord, key: string) => String(row[key] ?? '-')
async function load() { try { rows.value = await getQualityRecords('/quality/plans') } catch (e) { error.value = e instanceof Error ? e.message : '检验方案加载失败' } }
async function action(row: QualityRecord, name: string) { if (!row.id) return; try { await postQualityAction(`/quality/plans/${row.id}/${name}`); await load() } catch (e) { error.value = e instanceof Error ? e.message : '方案操作失败' } }
onMounted(load)
</script>
<template><MesLayout active="quality-plans"><header class="app-header"><div class="header-breadcrumb"><span>质量与追溯</span><span class="bc-sep">/</span><span class="bc-current">检验方案</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">检验方案</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>方案编码</th><th>方案名称</th><th>产品</th><th>客户</th><th>默认方案</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="7">暂无检验方案</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'planCode') }}</td><td>{{ value(row, 'planName') }}</td><td>{{ value(row, 'productId') }}</td><td>{{ value(row, 'customerId') }}</td><td>{{ value(row, 'defaultFlag') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><RouterLink :to="{ path: '/quality/plan-detail', query: { planId: row.id } }" class="btn btn-ghost btn-sm">明细</RouterLink><button class="btn btn-ghost btn-sm" @click="action(row, 'enable')">启用</button></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>检验方案 · {{ rows.length }} 条</span></footer></MesLayout></template>
