<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import MesLayout from '@/layouts/MesLayout.vue'
import { getQualityRecords, type QualityRecord } from '@/api/quality'
const route = useRoute(); const inspectionId = computed(() => String(route.query.inspectionId || '')); const rows = ref<QualityRecord[]>([]); const error = ref(''); const value = (row: QualityRecord, key: string) => String(row[key] ?? '-')
async function load() { if (!inspectionId.value) { error.value = '缺少检验单编号'; rows.value = []; return }; try { error.value = ''; rows.value = await getQualityRecords('/quality/inspection-results', { inspectionId: inspectionId.value }) } catch (e) { error.value = e instanceof Error ? e.message : '检验结果加载失败' } }
onMounted(load); watch(inspectionId, load)
</script>
<template><MesLayout active="quality-exec"><header class="app-header"><div class="header-breadcrumb"><span>质量与追溯</span><span class="bc-sep">/</span><RouterLink to="/quality-inspection">质量检验</RouterLink><span class="bc-sep">/</span><span class="bc-current">检验结果录入</span></div></header><main class="app-main"><h1 class="page-title">检验结果录入</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>结果ID</th><th>检验项</th><th>实测值</th><th>检验结果</th><th>缺陷原因</th><th>备注</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="6">暂无检验结果</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'id') }}</td><td>{{ value(row, 'qcItemId') }}</td><td>{{ value(row, 'measuredValue') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'result') }}</span></td><td>{{ value(row, 'defectReasonId') }}</td><td>{{ value(row, 'remark') }}</td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>检验单 #{{ inspectionId || '-' }} · {{ rows.length }} 项</span></footer></MesLayout></template>
