<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getQualityRecords, postQualityAction, type QualityRecord } from '@/api/quality'
const rows = ref<QualityRecord[]>([]); const error = ref(''); const value = (row: QualityRecord, key: string) => String(row[key] ?? '-')
async function load() { try { rows.value = await getQualityRecords('/quality/defect-records') } catch (e) { error.value = e instanceof Error ? e.message : '缺陷记录加载失败' } }
async function action(row: QualityRecord, name: string) { if (!row.id) return; try { await postQualityAction(`/quality/defect-records/${row.id}/${name}`); await load() } catch (e) { error.value = e instanceof Error ? e.message : '缺陷处理失败' } }
onMounted(load)
</script>
<template><MesLayout active="quality-defects"><header class="app-header"><div class="header-breadcrumb"><span>质量与追溯</span><span class="bc-sep">/</span><span class="bc-current">缺陷记录</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">缺陷记录</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>缺陷ID</th><th>来源类型</th><th>来源ID</th><th>产品</th><th>条码</th><th>缺陷原因</th><th>缺陷数量</th><th>处理方式</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="10">暂无缺陷记录</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'id') }}</td><td>{{ value(row, 'sourceType') }}</td><td>{{ value(row, 'sourceId') }}</td><td>{{ value(row, 'productId') }}</td><td>{{ value(row, 'barcodeId') }}</td><td>{{ value(row, 'defectReasonName') }}</td><td>{{ value(row, 'defectQty') }}</td><td>{{ value(row, 'handleMethod') }}</td><td><span class="badge badge-status-warn"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><button class="btn btn-ghost btn-sm" @click="action(row, 'start')">处理</button><button class="btn btn-ghost btn-sm" @click="action(row, 'complete')">完成</button><button class="btn btn-ghost btn-sm" @click="action(row, 'close')">关闭</button></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>缺陷记录 · {{ rows.length }} 条</span></footer></MesLayout></template>
