<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getQualityRecords, postQualityAction, type QualityRecord } from '@/api/quality'
const rows = ref<QualityRecord[]>([]); const error = ref(''); const value = (row: QualityRecord, key: string) => String(row[key] ?? '-')
async function load() { try { rows.value = await getQualityRecords('/quality/inspection-orders') } catch (e) { error.value = e instanceof Error ? e.message : '检验单加载失败' } }
async function action(row: QualityRecord, name: string) { if (!row.id) return; try { await postQualityAction(`/quality/inspection-orders/${row.id}/${name}`); await load() } catch (e) { error.value = e instanceof Error ? e.message : '检验状态更新失败' } }
onMounted(load)
</script>
<template><MesLayout active="quality-inspection"><header class="app-header"><div class="header-breadcrumb"><span>质量与追溯</span><span class="bc-sep">/</span><span class="bc-current">质量检验</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">质量检验</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>检验单号</th><th>检验类型</th><th>方案</th><th>生产工单</th><th>检验时间</th><th>最终结果</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="8">暂无检验单</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'inspectionNo') }}</td><td>{{ value(row, 'inspectionType') }}</td><td>{{ value(row, 'planId') }}</td><td>{{ value(row, 'workOrderId') }}</td><td>{{ value(row, 'inspectionAt') }}</td><td>{{ value(row, 'finalResult') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><RouterLink :to="{ path: '/quality/inspection-exec', query: { inspectionId: row.id } }" class="btn btn-ghost btn-sm">录入</RouterLink><button class="btn btn-ghost btn-sm" @click="action(row, 'start')">开始</button><button class="btn btn-ghost btn-sm" @click="action(row, 'pass')">合格</button><button class="btn btn-ghost btn-sm" @click="action(row, 'fail')">不合格</button></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>质量检验 · {{ rows.length }} 条</span></footer></MesLayout></template>
