<script setup lang="ts">
import { onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { getQualityRecords, postQualityAction, type QualityRecord } from '@/api/quality'
const rows = ref<QualityRecord[]>([]); const error = ref(''); const value = (row: QualityRecord, key: string) => String(row[key] ?? '-')
async function load() { try { rows.value = await getQualityRecords('/quality/item-categories') } catch (e) { error.value = e instanceof Error ? e.message : '分类加载失败' } }
async function action(row: QualityRecord, name: string) { if (!row.id) return; try { await postQualityAction(`/quality/item-categories/${row.id}/${name}`); await load() } catch (e) { error.value = e instanceof Error ? e.message : '分类操作失败' } }
onMounted(load)
</script>
<template><MesLayout active="quality-categories"><header class="app-header"><div class="header-breadcrumb"><span>质量与追溯</span><span class="bc-sep">/</span><span class="bc-current">检验项分类</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">检验项分类</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>分类编码</th><th>分类名称</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="4">暂无检验项分类</td></tr><tr v-for="row in rows" :key="row.id"><td class="cell-mono">{{ value(row, 'categoryCode') }}</td><td>{{ value(row, 'categoryName') }}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{ value(row, 'status') }}</span></td><td class="cell-actions"><button class="btn btn-ghost btn-sm" @click="action(row, 'enable')">启用</button><button class="btn btn-ghost btn-sm" @click="action(row, 'disable')">停用</button></td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>检验项分类 · {{ rows.length }} 条</span></footer></MesLayout></template>
