<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { get } from '@/api/client'
import OutputBarChart from '@/components/OutputBarChart.vue'

type OutputRow = { statDate?: string; lineName?: string; lineCode?: string; outputQty?: number; reportedQty?: number; qualifiedQty?: number; defectiveQty?: number }
const rows = ref<OutputRow[]>([]), loading = ref(false), error = ref('')
const activeTab = ref<'daily' | 'weekly' | 'monthly' | 'product'>('daily')
const value = (row: OutputRow) => Number(row.outputQty ?? row.reportedQty ?? 0)
const points = computed(() => { const grouped = new Map<string, number>(); rows.value.forEach(row => { const key = row.statDate || '未标注'; grouped.set(key, (grouped.get(key) || 0) + value(row)) }); return [...grouped].sort(([left], [right]) => left.localeCompare(right)).map(([label, value]) => ({ label: label.slice(5), value })) })
const total = computed(() => rows.value.reduce((sum, row) => sum + value(row), 0))
const average = computed(() => points.value.length ? Math.round(total.value / points.value.length) : 0)
const peak = computed(() => Math.max(...points.value.map(point => point.value), 0))
async function load() { loading.value = true; error.value = ''; try { rows.value = await get<OutputRow[]>('/report/production-output/daily') } catch (e) { error.value = e instanceof Error ? e.message : '产量报表加载失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template><MesLayout active="reports-output"><header class="app-header"><div class="header-breadcrumb"><span>数据与系统</span><span class="bc-sep">/</span><span class="bc-current">产量报表</span></div><div class="header-actions"><button class="btn btn-secondary btn-sm" :disabled="loading" @click="load">导出 Excel</button><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">产量报表</h1><div class="tabs"><span class="tab-item" :class="{active:activeTab==='daily'}" @click="activeTab='daily'">日报</span><span class="tab-item" :class="{active:activeTab==='weekly'}" @click="activeTab='weekly'">周报</span><span class="tab-item" :class="{active:activeTab==='monthly'}" @click="activeTab='monthly'">月报</span><span class="tab-item" :class="{active:activeTab==='product'}" @click="activeTab='product'">按产品</span></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{error}}</div><div v-if="activeTab==='daily'" class="kpi-grid mb-5"><div class="kpi-card accent-border"><span class="kpi-label">今日产量</span><strong class="kpi-value">{{total.toLocaleString()}}</strong><span class="kpi-change">台</span></div><div class="kpi-card"><span class="kpi-label">日均产量（本月）</span><strong class="kpi-value">{{average.toLocaleString()}}</strong><span class="kpi-change">台 / 天</span></div><div class="kpi-card"><span class="kpi-label">峰值产能</span><strong class="kpi-value">{{peak.toLocaleString()}}</strong><span class="kpi-change">台 / 天</span></div><div class="kpi-card"><span class="kpi-label">本月累计</span><strong class="kpi-value">{{total.toLocaleString()}}</strong><span class="kpi-change">台</span></div></div><section v-if="activeTab==='daily'" class="card mb-5"><div class="card-header"><h2 class="card-title">近 7 天产量趋势</h2></div><OutputBarChart :points="points" /></section><div class="data-table-wrap"><table class="data-table"><thead><tr><th>{{activeTab==='product'?'产品/规格':'日期'}}</th><th>产线</th><th>产量</th><th>合格数量</th><th>不良数量</th></tr></thead><tbody><tr v-if="loading"><td colspan="5">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="5">暂无产量数据</td></tr><tr v-for="(row,index) in rows" :key="`${row.statDate||''}-${row.lineCode||index}`"><td>{{activeTab==='product'?(row.lineName||row.lineCode||'-'):(row.statDate||'-')}}</td><td>{{row.lineName||row.lineCode||'-'}}</td><td>{{value(row)}}</td><td>{{row.qualifiedQty??'-'}}</td><td>{{row.defectiveQty??'-'}}</td></tr></tbody></table></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>系统正常</span><span class="statusbar-sep">|</span><span class="statusbar-item">产量报表 · {{rows.length}} 条</span></footer></MesLayout></template>
