<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import MesLayout from '@/layouts/MesLayout.vue'
import { del,get,post } from '@/api/client'
type Binding={id:number;bindingType:string;productId?:number;routeId?:number;routeStepId?:number;processId?:number;workstationId?:number;equipmentId?:number;taskId?:number;priority?:number;status?:string}
const route=useRoute(),versionId=computed(()=>Number(route.query.versionId||0)),rows=ref<Binding[]>([]),error=ref(''),loading=ref(false),creating=ref(false);const form=ref({bindingType:'PROCESS',targetId:'',priority:'10',confirmMode:'PER_TASK',status:'ACTIVE'})
function target(row:Binding){return [['产品',row.productId],['路线',row.routeId],['路线工序',row.routeStepId],['工序',row.processId],['工位',row.workstationId],['设备',row.equipmentId],['任务',row.taskId]].filter(([,v])=>v!=null).map(([k,v])=>`${k}: ${v}`).join('；')||'-'}
async function load(){if(!versionId.value){rows.value=[];error.value='请从版本页面进入绑定配置';return};loading.value=true;error.value='';try{rows.value=await get<Binding[]>(`/production/sop/versions/${versionId.value}/bindings`)}catch(e){error.value=e instanceof Error?e.message:'绑定加载失败'}finally{loading.value=false}}
async function create(){try{const id=Number(form.value.targetId);const target={productId:form.value.bindingType==='PRODUCT'?id:null,routeId:form.value.bindingType==='ROUTE'?id:null,routeStepId:form.value.bindingType==='ROUTE_STEP'?id:null,processId:form.value.bindingType==='PROCESS'?id:null,workstationId:form.value.bindingType==='WORKSTATION'?id:null,equipmentId:form.value.bindingType==='EQUIPMENT'?id:null,taskId:form.value.bindingType==='TASK'?id:null};await post(`/production/sop/versions/${versionId.value}/bindings`,{bindingType:form.value.bindingType,...target,priority:Number(form.value.priority||10),confirmMode:form.value.confirmMode,status:form.value.status});creating.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'创建绑定失败'}}
async function remove(row:Binding){if(!confirm('确定删除此绑定吗？'))return;try{await del(`/production/sop/bindings/${row.id}`);await load()}catch(e){error.value=e instanceof Error?e.message:'删除绑定失败'}}
onMounted(load);watch(versionId,load)
</script>
<template><MesLayout active="sop-bindings"><header class="app-header"><div class="header-breadcrumb"><span>电子 SOP</span><span class="bc-sep">/</span><span class="bc-current">绑定配置</span></div><div class="header-actions"><button class="btn btn-primary btn-sm" :disabled="!versionId" @click="creating=true">+ 新建绑定</button><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">SOP 绑定配置</h1><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{error}}</div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>绑定类型</th><th>绑定对象</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="5">正在加载...</td></tr><tr v-else-if="!rows.length"><td colspan="5">暂无绑定</td></tr><tr v-for="row in rows" :key="row.id"><td>{{row.bindingType}}</td><td>{{target(row)}}</td><td>{{row.priority??'-'}}</td><td><span class="badge badge-status-ok"><span class="badge-dot"></span>{{row.status||'-'}}</span></td><td><button class="btn btn-ghost btn-sm" @click="remove(row)">删除</button></td></tr></tbody></table><div class="pagination">共 {{rows.length}} 条绑定</div></div><div v-if="creating" class="sop-mask" @click.self="creating=false"><form class="sop-dialog" @submit.prevent="create"><div class="card-header"><h2 class="card-title">新建 SOP 绑定</h2></div><label>绑定类型<select v-model="form.bindingType" class="form-select"><option value="PRODUCT">产品</option><option value="ROUTE">路线</option><option value="ROUTE_STEP">路线工序</option><option value="PROCESS">工序</option><option value="WORKSTATION">工位</option><option value="EQUIPMENT">设备</option><option value="TASK">任务</option></select></label><label>对象 ID<input v-model="form.targetId" class="form-input" inputmode="numeric" required></label><label>优先级<input v-model="form.priority" class="form-input" type="number" min="1"></label><label>确认模式<select v-model="form.confirmMode" class="form-select"><option value="PER_TASK">每任务确认</option><option value="PER_UNIT">每件确认</option></select></label><label>状态<select v-model="form.status" class="form-select"><option value="ACTIVE">启用</option><option value="INACTIVE">停用</option></select></label><div class="dialog-actions"><button type="button" class="btn btn-secondary" @click="creating=false">取消</button><button class="btn btn-primary">保存</button></div></form></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>绑定配置</span></footer></MesLayout></template>
<style scoped>.sop-mask{position:fixed;inset:0;z-index:20;background:rgba(15,23,42,.38);display:grid;place-items:center}.sop-dialog{width:min(460px,calc(100vw - 32px));background:#fff;border-radius:8px;padding:20px;box-shadow:0 18px 50px rgba(15,23,42,.28);display:grid;gap:14px}.sop-dialog label{display:grid;gap:7px;font-size:13px}.dialog-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:8px}</style>
