<script setup lang="ts">
import { ref } from 'vue'
import MesLayout from '@/layouts/MesLayout.vue'
import { get } from '@/api/client'
type TraceEvent = { id: number; eventAt: string; eventType: string; processName?: string; stationName?: string; barcode: string; workOrderNo?: string; operatorName?: string; equipmentName?: string; result?: string }
type TraceResult = { root: string; nodes: Array<{ id: string; title: string; relation: string }>; events: TraceEvent[] }
const keyword = ref(''); const result = ref<TraceResult | null>(null); const error = ref(''); const loading = ref(false)
async function query() { if (!keyword.value.trim()) return; loading.value = true; error.value = ''; try { result.value = await get<TraceResult>(`/production/trace/${encodeURIComponent(keyword.value.trim())}`) } catch (e) { error.value = e instanceof Error ? e.message : '追溯查询失败' } finally { loading.value = false } }
</script>
<template><MesLayout active="trace"><header class="app-header"><div class="header-breadcrumb"><span>条码与追溯</span><span class="bc-sep">/</span><span class="bc-current">追溯查询</span></div><div class="header-actions"><span class="user-avatar">张</span></div></header><main class="app-main"><h1 class="page-title">追溯查询</h1><div class="card mb-5" style="max-width:700px"><div class="search-bar" style="margin-bottom:0"><div class="form-group" style="min-width:360px"><label class="form-label">条码、工单或批次</label><input v-model="keyword" class="form-input" placeholder="输入查询关键字" @keydown.enter="query"></div><button class="btn btn-primary btn-sm" :disabled="loading" style="align-self:flex-end" @click="query">{{ loading ? '查询中...' : '查询追溯' }}</button></div></div><div v-if="error" class="alert alert-error mb-5"><span class="alert-icon">!</span>{{ error }}</div><div v-if="result"><h2 class="section-title">追溯链路 · {{ result.root }}</h2><div class="card mb-5"><div class="timeline"><div v-for="(node, index) in result.nodes" :key="node.id" class="timeline-step done"><span class="step-dot">{{ index + 1 }}</span><span class="step-label">{{ node.title }}</span><span class="text-muted">{{ node.relation }}</span></div></div></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>事件时间</th><th>事件类型</th><th>工序/工位</th><th>条码</th><th>关联工单</th><th>作业员</th><th>设备</th><th>结果</th></tr></thead><tbody><tr v-if="!result.events.length"><td colspan="8">暂无追溯事件</td></tr><tr v-for="event in result.events" :key="event.id"><td>{{ event.eventAt.replace('T', ' ') }}</td><td>{{ event.eventType }}</td><td>{{ event.processName || event.stationName || '-' }}</td><td class="cell-mono">{{ event.barcode }}</td><td>{{ event.workOrderNo || '-' }}</td><td>{{ event.operatorName || '-' }}</td><td>{{ event.equipmentName || '-' }}</td><td>{{ event.result || '-' }}</td></tr></tbody></table></div></div></main><footer class="app-statusbar"><span class="statusbar-item"><span class="dot ok"></span>追溯查询</span></footer></MesLayout></template>
